Controllers/SanPhamBanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnWebbb.Models;
using PagedList;
using PagedList.Mvc;

namespace DoAnWebbb.Controllers
{
    public class SanPhamBanController : Controller
    {
        // GET: SanPhamBan
        MyDataDataContext db = new MyDataDataContext();
        public ActionResult Index(int? page)
        {
            ViewBag.MacDinh = db.SANPHAMs.ToList();
            ViewBag.Moi = db.SANPHAMs.ToList().OrderBy(n => n.NGAYCAPNHAT);
            ViewBag.GiaCao = db.SANPHAMs.ToList().OrderByDescending(n => n.GIAGIAM);
            ViewBag.GiaThap = db.SANPHAMs.ToList().OrderBy(n => n.GIAGIAM);
            int pageSize = 10;
            int pageNum = (page ?? 1);
            return View(db.SANPHAMs.ToPagedList(pageNum, pageSize));
        }
        public ActionResult HangMay()
        {
            var hangmay = from hang in db.NHACUNGCAPs select hang;
            return PartialView(hangmay);
        }
        public ActionResult LoaiMay()
        {
            var loaimay = from loai in db.LOAIMAYs select loai;
            return PartialView(loaimay);
        }
        public ActionResult SPTheoHang(int id)
        {
            var sanpham = from sp in db.SANPHAMs where sp.MASANPHAM == id select sp;
            return View(sanpham);
        }
        public ActionResult SPTheoLoai(int id)
        {
            var sanpham = from sp in db.SANPHAMs where sp.MASANPHAM == id select sp; ;
            return View(sanpham);
        }
    }
}

Views/SanPhamBan/HangMay.cshtml
@model IEnumerable<DoAnWebbb.Models.NHACUNGCAP>
<p class="lead">HÃNG MÁY</p>
<div class="list-group">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("SPTheoHang", "SanPhamBan", new { id = item.MANCC})" class="list-group-item" style="color:black">
            @item.TENNCCC
        </a>
    }
</div>

Views/SanPhamBan/Index.cshtml
@using DoAnWebbb.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<SANPHAM>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/New.cshtml";
}
<body>
    <section class="food_section">
        <div class="container">
            <div class="filters-content">
                <div class="row">
                    @foreach (var item in Model)
                    {
                        <div class="col-sm-6 col-lg-4 all pizza">

                            <div class="box">
                                <div>
                                    <div class="img-box">
                                        <img src="@item.HINH" alt="thumbnails" />
                                    </div>
                                    <div class="detail-box">
                                        <h5>
                                            @item.TENSANPHAM
                                        </h5>
                            
                                        <div class="options">
                                            <h6>
                                                <bdo>$</bdo>@String.Format("{0:0,0}", item.GIABAN) <bdo>VNĐ</bdo>
                                            </h6>
                                            <a class="btn btn-success" href="@Url.Action("ThemGioHang", "GioHang",new { @id = item.MASANPHAM, @strURL = Request.Url.ToString() })">Đặt mua</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    }
                </div>
            </div>
        </div>
    </section>

    @*Trang @(Model.PageCount<Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
        </div>
        <style>
            .MenuTrang li {
                display: inline;
            }
        </style>*@

</body>

Views/SanPhamBan/LoaiMay.cshtml
@model IEnumerable<DoAnWebbb.Models.LOAIMAY>
<p class="lead" style="margin-top: 15px">LOẠI MÁY</p>
<div class="list-group">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("SPTheoLoai", "SanPhamBan", new { id = item.MALOAI})" class="list-group-item" style="color:black">
            @item.TENLOAI
        </a>
    }
</div>

Views/SanPhamBan/SPTheoHang.cshtml
@model IEnumerable<DoAnWebbb.Models.SANPHAM>

@{
    ViewBag.Title = "SPTheoHang";
    Layout = "~/Views/Shared/New.cshtml";
}

<body>
    <section class="food_section">
        <div class="container">
         
            <div class="filters-content">
                <div class="row">
                    @foreach (var item in Model)
                    {
                        <div class="col-sm-6 col-lg-4 all pizza">

                            <div class="box">
                                <div>
                                    <div class="img-box">
                                        <img src="@item.HINH" alt="thumbnails" />
                                    </div>
                                    <div class="detail-box">
                                        <h5>
                                            @item.TENSANPHAM
                                        </h5>
                                        <p>
                                            @item.MOTASANPHAM
                                        </p>
                                        <div class="options">
                                            <h6>
                                                <bdo>$</bdo>@String.Format("{0:0,0}", item.GIABAN) <bdo>VNĐ</bdo>
                                            </h6>
                                            <a class="btn btn-success" href="@Url.Action("ThemGioHang", "GioHang",new { @id = item.MASANPHAM, @strURL = Request.Url.ToString() })">Đặt mua</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    }
                </div>
            </div>
        </div>
    </section>

    @*Trang @(Model.PageCount<Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
        </div>
        <style>
            .MenuTrang li {
                display: inline;
            }
        </style>*@

</body>

Views/SanPhamBan/SPTheoLoai.cshtml
@model IEnumerable<DoAnWebbb.Models.SANPHAM>

@{
    ViewBag.Title = "SPTheoLoai";
    Layout = "~/Views/Shared/New.cshtml";
}

<body>
    <section class="food_section">
        <div class="container">
            <div class="filters-content">
                <div class="row">
                    @foreach (var item in Model)
                    {
                        <div class="col-sm-6 col-lg-4 all pizza">

                            <div class="box">
                                <div>
                                    <div class="img-box">
                                        <img src="@item.HINH" alt="thumbnails" />
                                    </div>
                                    <div class="detail-box">
                                        <h5>
                                            @item.TENSANPHAM
                                        </h5>
                                        <p>
                                            @item.MOTASANPHAM
                                        </p>
                                        <div class="options">
                                            <h6>
                                                <bdo>$</bdo>@String.Format("{0:0,0}", item.GIABAN) <bdo>VNĐ</bdo>
                                            </h6>
                                            <a class="btn btn-success" href="@Url.Action("ThemGioHang", "GioHang",new { @id = item.MASANPHAM, @strURL = Request.Url.ToString() })">Đặt mua</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    }
                </div>
            </div>
        </div>
    </section>

    @*Trang @(Model.PageCount<Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
        </div>
        <style>
            .MenuTrang li {
                display: inline;
            }
        </style>*@

</body>