Areas/Admin/Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnWebbb.Models;
using PagedList;
using PagedList.Mvc;

namespace DoAnWebbb.Areas.Admin.Controllers
{
    public class DonHangController : Controller
    {
        MyDataDataContext db = new MyDataDataContext();
        // GET: Admin/DonHang
        public ActionResult Index(int?page)
        {
            int pageNum = (page ?? 1);
            int pageSize = 10;
            return View(db.PHIEUMUAs.ToList().OrderBy(n => n.NGAYDAT).ToPagedList(pageNum, pageSize));
        }
        public ActionResult ChiTietDonHang(int id)
        {
            //Lấy ra đối tượng sách theo mã
            PHIEUMUA donhang = db.PHIEUMUAs.SingleOrDefault(n => n.MAPHIEUMUA == id);
            ViewBag.MaPhieuMua = donhang.MAPHIEUMUA;
            if (donhang == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(donhang);
        }
    }
}

Areas/Admin/Views/DonHang/ChiTietDonHang.cshtml
@model DoAnWebbb.Models.PHIEUMUA

@{
    ViewBag.Title = "Chi Tiết Đơn Hàng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutHomeAdmin.cshtml";
    double tongtien = 0;
}

<div class="box">
    <h2 style="text-align:center; color: black; margin-top:10px">Thông Tin Khách Hàng</h2>

    <div class="box-body">

        <div>
            <div>
                <form method="POST">
                    <div class="panel panel-title">
                        <div class="panel-body">
                            <table class="table">
                                <tbody>
                                    <tr style="color:black">
                                        <td>Tên khách hàng</td>
                                        <td>Ngày đặt hàng</td>
                                        <td>Số điện thoại</td>
                                        <td>Địa chỉ</td>
                                        <td>Email</td>
                                    </tr>
                                    <tr style="color:black">
                                        <td>@Html.DisplayFor(model => model.NGUOIDUNG.HOVATEN)</td>
                                        <td>@Html.DisplayFor(model => model.NGAYDAT)</td>
                                        <td>@Html.DisplayFor(model => model.NGUOIDUNG.SDT)</td>
                                        <td>@Html.DisplayFor(model => model.DIACHIGIAOHANG)</td>
                                        <td>@Html.DisplayFor(model => model.NGUOIDUNG.GMAIL)</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div style="color:black; margin-left: 10px">
                        @if (Model.TRANGTHAI == 0)
                        {
                            <input hidden name="Status" value="1" />
                            <p>
                                Trạng thái giao hàng: <label class="btn btn-primary">Đang chờ</label>
                                Xử lý <button type="submit" value="1" class="btn btn-primary">Xác nhận</button>
                            </p> }
                        else if (Model.TRANGTHAI == 1)
                        {
                            <input hidden name="Status" value="2" />
                            <p>
                                Trạng thái giao hàng:  <label class="btn btn-primary">Xác Nhận</label>
                                Xử lý <button type="submit" value="2" class="btn btn-primary">Đang giao</button>
                            </p> }
                        else if (Model.TRANGTHAI == 2)
                        {
                            <input hidden name="Status" value="3" />
                            <p>
                                Trạng thái giao hàng:  <label class="btn btn-primary">Đang giao</label>
                                Xử lý <button type="submit" class="btn btn-primary">Đã giao</button>
                            </p> }
                        else
                        {
                            <p>
                                Trạng thái giao hàng:  <label class="btn btn-primary">Hoàn thành</label>
                            </p>
                        }
                    </div>
                </form>
            </div>
            <h2 style="text-align:center; color: black; margin-top:10px">Chi Tiết Đơn Hàng</h2>

        </div>
    </div>
    <div>
        <a class="btn btn-primary" href="@Url.Action("Index")" style="margin-left: 10px; margin-bottom:5px">Quay về</a>
    </div>
</div>

Areas/Admin/Views/DonHang/Index.cshtml
@using DoAnWebbb.Models
@using PagedList.Mvc;
@model PagedList.PagedList<DoAnWebbb.Models.PHIEUMUA>

@{
    ViewBag.Title = "ĐƠN HÀNG";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutHomeAdmin.cshtml";
}
<div>
    <div class="box">
        <h2 style="text-align:center; color: black; margin-top:10px">Quản Lý Đơn Hàng</h2>
        <div class="box-body">
            <table id="example1" class="table table-bordered table-hover">
                <thead style="color:black; text-align:center">
                    <tr>
                        <th>
                            Tài Khoản
                        </th>
                        <th>
                            Họ Và Tên
                        </th>
                        <th>
                            Gmail
                        </th>
                        <th>
                            Số Điện Thoại
                        </th>
                        <th>
                            Địa Chỉ Giao Hàng
                        </th>
                        <th>
                            Ngày Đặt
                        </th>
                        <th>
                            Trạng Thái
                        </th>
                        <th>
                            Tác Vụ
                        </th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr style="color:black">
                            <td>
                                @Html.DisplayFor(modelItem => item.USERNAME)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NGUOIDUNG.HOVATEN)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NGUOIDUNG.GMAIL)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NGUOIDUNG.SDT)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DIACHIGIAOHANG)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NGAYDAT)
                            </td>
                            <td>
                                @if (item.TRANGTHAI == 0)
                                {
                                    <label class="btn btn-primary">Đang chờ</label> }
                                else if (item.TRANGTHAI == 1)
                                {
                                    <label class="btn btn-primary">Xác Nhận</label> }
                                else if (item.TRANGTHAI == 2)
                                {
                                    <label class="btn btn-primary">Đang giao</label> }
                                else
                                {
                                    <label class="btn btn-success">Hoàn thành</label>}
                            </td>
                            <td class="chitietdon">
                                <a class="btn btn-primary" style="font-size:10px;" href="@Url.Action("ChiTietDonHang","DonHang",new { id=item.MAPHIEUMUA })"><i class="fa fa-fw fa-pen"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>